version: '3.8'

services:
  telegram-bot:
    container_name: telegram-bot
    working_dir: /tg-bot-for-bank
    env_file:
      - .env
    restart: always
    build: .
    command: sh -c "PYTHONPATH=/tg-bot-for-bank python tg_bot_for_bank/bot.py"
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5435:5432"  # Хостовый порт 5435, перенаправляемый на контейнерный порт 5432
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
